name: CI - Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  construir:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Dar permisos a Maven Wrapper
        run: chmod +x mvnw

      - name: Compilar, ejecutar pruebas y analizar con SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ianreyescollao_eva1-devops -Dsonar.qualitygate.wait=true

      - name: Construir imagen docker
        run: docker build -t msvc-ingrediente .
